version: '3'
# Define services
services:
  api:
    # Configuration for building the docker image for the service
    build: .
    container_name: api
    entrypoint: sh ./scripts/entrypoint.sh
    environment:
      - HOST_PWD=$PWD
      - SAM_CLI_TELEMETRY=0
    networks:
      - local
    ports:
      - "3000:3000" # Forward the exposed port 3000 on the container to port 3000 on the host machine
    restart: unless-stopped
    volumes:
      - .:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      # a container, with Docker installed, does not run its own Docker daemon
      # but connects to the Docker daemon of the host system.
      # That means, you will have a Docker CLI in the container
      # as well as on the host system, but they both connect to
      # one and the same Docker daemon. At any time, there is only
      # one Docker daemon running in your machine, the one running on the host system.
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge