AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: go-serverless-docker-compose
Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      Events:
        SampleEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  World:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/world
      Runtime: go1.x
      Events:
        SampleEvent:
          Type: Api
          Properties:
            Path: /world
            Method: get
